# Add configuration values here, as shown below.
#
 pusher_app_id: "AC0c67c9223d71aea93cf4070658201a0e"
 pusher_key: 'f3000c8971c9f30db04b3da65903ae5b'
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
